//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BHIPEntities : DbContext
    {
        public BHIPEntities()
            : base("name=BHIPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<MenuRole> MenuRoles { get; set; }
        public virtual DbSet<ContactSchedule> ContactSchedules { get; set; }
        public virtual DbSet<EntityType> EntityTypes { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<DriverInfoSchedule> DriverInfoSchedules { get; set; }
        public virtual DbSet<PolicyYear> PolicyYears { get; set; }
        public virtual DbSet<Premium> Premiums { get; set; }
        public virtual DbSet<VehicleSchedule> VehicleSchedules { get; set; }
        public virtual DbSet<MemberStatu> MemberStatus { get; set; }
        public virtual DbSet<OwnLease> OwnLeases { get; set; }
        public virtual DbSet<ConstructionType> ConstructionTypes { get; set; }
        public virtual DbSet<FireBurglar> FireBurglars { get; set; }
        public virtual DbSet<BoardCertified> BoardCertifieds { get; set; }
        public virtual DbSet<BoardEligible> BoardEligibles { get; set; }
        public virtual DbSet<EmploymentType> EmploymentTypes { get; set; }
        public virtual DbSet<Malpractice> Malpractices { get; set; }
        public virtual DbSet<SpecialtyType> SpecialtyTypes { get; set; }
        public virtual DbSet<PrimaryCareSchedule> PrimaryCareSchedules { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<ReportParam> ReportParams { get; set; }
        public virtual DbSet<ReportParamType> ReportParamTypes { get; set; }
        public virtual DbSet<ReportRole> ReportRoles { get; set; }
        public virtual DbSet<ReportTrust> ReportTrusts { get; set; }
        public virtual DbSet<ReportType> ReportTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ScheduleStatu> ScheduleStatus { get; set; }
        public virtual DbSet<PrimaryCareScheduleHold> PrimaryCareScheduleHolds { get; set; }
        public virtual DbSet<VehicleScheduleHold> VehicleScheduleHolds { get; set; }
        public virtual DbSet<ContactScheduleHold> ContactScheduleHolds { get; set; }
        public virtual DbSet<DriverInfoScheduleHold> DriverInfoScheduleHolds { get; set; }
        public virtual DbSet<MemberCoverage> MemberCoverages { get; set; }
        public virtual DbSet<PropertySchedule> PropertySchedules { get; set; }
        public virtual DbSet<PropertyScheduleHold> PropertyScheduleHolds { get; set; }
        public virtual DbSet<QuestionAnswer> QuestionAnswers { get; set; }
        public virtual DbSet<QuestionSection> QuestionSections { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<LicenseSchedule> LicenseSchedules { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<HandleFund> HandleFunds { get; set; }
        public virtual DbSet<InspectionBody> InspectionBodies { get; set; }
        public virtual DbSet<AgencyPlanSchedule> AgencyPlanSchedules { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<Renewal> Renewals { get; set; }
        public virtual DbSet<PsychiatrySchedule> PsychiatrySchedules { get; set; }
        public virtual DbSet<PsychiatryScheduleHold> PsychiatryScheduleHolds { get; set; }
        public virtual DbSet<OtherSchedule> OtherSchedules { get; set; }
        public virtual DbSet<OtherScheduleHold> OtherScheduleHolds { get; set; }
        public virtual DbSet<PremiumHold> PremiumHolds { get; set; }
        public virtual DbSet<t_Users> t_Users { get; set; }
        public virtual DbSet<CustomParam> CustomParams { get; set; }
        public virtual DbSet<CustomParamType> CustomParamTypes { get; set; }
        public virtual DbSet<CustomReport> CustomReports { get; set; }
        public virtual DbSet<CustomReportType> CustomReportTypes { get; set; }
        public virtual DbSet<CustomRole> CustomRoles { get; set; }
        public virtual DbSet<JobFunction> JobFunctions { get; set; }
    }
}
