//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomParam
    {
        public int CustomParamID { get; set; }
        public int CustomReportID { get; set; }
        public int CustomParamTypeID { get; set; }
        public string ParamName { get; set; }
        public string ParamTitle { get; set; }
        public Nullable<int> ParamWidth { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string DropSQL { get; set; }
    }
}
