//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandleFund
    {
        public int HandleFundsID { get; set; }
        public int RenewalID { get; set; }
        public string JobFunction { get; set; }
        public Nullable<int> NumOfEmployees { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public bool IsActive { get; set; }
    }
}
