//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionBody
    {
        public int InspectBodyID { get; set; }
        public int RenewalID { get; set; }
        public string InspectName { get; set; }
        public string InspectType { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string DateDeleted { get; set; }
    }
}
