//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberCoverage
    {
        public int MemberCoverageID { get; set; }
        public string MemberName { get; set; }
        public int MemberId { get; set; }
        public string MemberPhone { get; set; }
        public string MemberPhoneExt { get; set; }
        public string MemberWebsite { get; set; }
        public string FederalID { get; set; }
        public Nullable<int> EntityTypeID { get; set; }
        public Nullable<System.DateTime> JoinedBHIP { get; set; }
        public Nullable<System.DateTime> TerminatedBHIP { get; set; }
        public Nullable<int> CurrentStatusID { get; set; }
        public string PrimaryAddress1 { get; set; }
        public string PrimaryAddress2 { get; set; }
        public string PrimaryCity { get; set; }
        public string PrimaryZip { get; set; }
        public Nullable<int> PrimaryStateID { get; set; }
        public string MailAddress1 { get; set; }
        public string MailAddress2 { get; set; }
        public string MailCity { get; set; }
        public Nullable<int> MailStateID { get; set; }
        public string MailZip { get; set; }
        public string ContactPrefix { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactTitle { get; set; }
        public string ContactPhone { get; set; }
        public string ContactPhoneExt { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<bool> IsBoardMember { get; set; }
        public string AuthorizePrefix { get; set; }
        public string AuthorizeFirstName { get; set; }
        public string AuthorizeLastName { get; set; }
        public string AuthorizeTitle { get; set; }
        public string AuthorizeAddress1 { get; set; }
        public string AuthorizeAddress2 { get; set; }
        public string AuthorizeCity { get; set; }
        public Nullable<int> AuthorizeStateID { get; set; }
        public string AuthorizeZip { get; set; }
        public string AuthorizePhone { get; set; }
        public string AuthorizePhoneExt { get; set; }
        public string AuthorizeEmail { get; set; }
        public string MemberNameAbbr { get; set; }
        public Nullable<System.DateTime> OperationsStartDate { get; set; }
    }
}
