//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PsychiatryScheduleHold
    {
        public int PsychiatryScheduleHoldID { get; set; }
        public int PsychiatryScheduleID { get; set; }
        public int MemberCoverageID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SpecialtyID { get; set; }
        public Nullable<System.DateTime> RetroDate { get; set; }
        public Nullable<int> BoardCertifiedID { get; set; }
        public Nullable<int> BoardEligibleID { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public Nullable<int> ContractorEmployeeID { get; set; }
        public Nullable<int> OwnMalpracticeID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateRemoved { get; set; }
        public string EditType { get; set; }
        public bool COI { get; set; }
        public int ScheduleStatusID { get; set; }
        public string UserID { get; set; }
        public string SpecialtyOther { get; set; }
    }
}
