//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QuestionID { get; set; }
        public int QuestionSectionID { get; set; }
        public Nullable<int> QuestionNumber { get; set; }
        public Nullable<int> QuestionOrder { get; set; }
        public string Question1 { get; set; }
        public string DropDown { get; set; }
        public string QuestionType { get; set; }
        public bool IsActive { get; set; }
        public bool IsRequired { get; set; }
        public string Class { get; set; }
    }
}
