//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionSection
    {
        public int QuestionSectionID { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> SectionOrder { get; set; }
        public string SectionText { get; set; }
        public string HeaderText { get; set; }
        public string FooterText { get; set; }
        public bool IsActive { get; set; }
    }
}
