//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHIP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSchedule
    {
        public int VehicleScheduleID { get; set; }
        public int MemberCoverageID { get; set; }
        public Nullable<int> Year { get; set; }
        public string MakeModel { get; set; }
        public string City { get; set; }
        public Nullable<int> StateID { get; set; }
        public string Zipcode { get; set; }
        public string VIN { get; set; }
        public Nullable<int> OwnLeaseID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> VehicleValue { get; set; }
    }
}
